# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ahegui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(654, 491)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(430, 10, 201, 261))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 158, 44))
        self.label.setObjectName("label")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(60, 40, 104, 31))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 158, 69))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 91, 51))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 158, 51))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 90, 104, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(60, 130, 104, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(60, 170, 104, 31))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 191, 131))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(210, 10, 191, 131))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(210, 150, 191, 131))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 150, 191, 131))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 54, 12))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(100, 310, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 380, 351, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(480, 370, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ICU患者急性低血压预警系统V1.0"))
        self.groupBox.setTitle(_translate("Form", "患者基本信息"))
        self.label.setText(_translate("Form", "患者ID："))
        self.label_4.setText(_translate("Form", "性别："))
        self.label_5.setText(_translate("Form", "姓名："))
        self.label_3.setText(_translate("Form", "年龄："))
        self.label_2.setText(_translate("Form", "模型选择"))
        self.comboBox.setItemText(0, _translate("Form", "GBDT"))
        self.comboBox.setItemText(1, _translate("Form", "SVM"))
        self.comboBox.setItemText(2, _translate("Form", "LR"))
        self.comboBox.setItemText(3, _translate("Form", "XGB"))
        self.comboBox.setItemText(4, _translate("Form", "RF"))
        self.comboBox.setItemText(5, _translate("Form", "AdaBoost"))
        self.comboBox.setItemText(6, _translate("Form", "Ensemble"))
        self.groupBox_2.setTitle(_translate("Form", "动态预测结果"))
        self.label_10.setText(_translate("Form", "发生AHE的概率："))
        self.pushButton.setText(_translate("Form", "开始预测"))
